# Generated by Django 2.0.7 on 2018-08-07 07:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '一级评论', 'verbose_name_plural': '一级评论'},
        ),
        migrations.AlterModelOptions(
            name='subcomment',
            options={'verbose_name': '二级评论', 'verbose_name_plural': '二级评论'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AddField(
            model_name='tag',
            name='desc',
            field=models.CharField(blank=True, help_text='标签描述', max_length=128, null=True, verbose_name='标签描述'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(help_text='作者', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='内容', max_length=20480, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, help_text='主图', null=True, upload_to='article_images', verbose_name='主图'),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='发布时间', verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(help_text='摘要', max_length=514, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='标签', related_name='articles', to='articles.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='标题', max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, help_text='阅读数', verbose_name='阅读数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(help_text='从属文章', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Article', verbose_name='从属文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='评论人', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='评论内容', max_length=256, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='评论时间', verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='article',
            field=models.ForeignKey(help_text='从属文章', on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='从属文章'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='author',
            field=models.ForeignKey(help_text='评论人', on_delete=django.db.models.deletion.CASCADE, related_name='sub_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='content',
            field=models.TextField(help_text='评论内容', max_length=256, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='parent_comment',
            field=models.ForeignKey(help_text='父评论', on_delete=django.db.models.deletion.CASCADE, related_name='sub_comments', to='articles.Comment', verbose_name='父评论'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='评论时间', verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='reply_to',
            field=models.ForeignKey(help_text='回复给', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回复给'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='chinese_name',
            field=models.CharField(blank=True, help_text='标签中文名', max_length=32, null=True, verbose_name='标签中文名'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='标签名', max_length=32, unique=True, verbose_name='标签名'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='标签slug', unique=True, verbose_name='标签slug'),
        ),
    ]
