# Generated by Django 2.0.7 on 2018-08-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='电子邮箱', max_length=254, null=True, verbose_name='电子邮箱'),
        ),
    ]
