# Generated by Django 2.0.7 on 2018-08-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='头像url', null=True, verbose_name='头像url'),
        ),
    ]
