# Generated by Django 2.0.7 on 2018-07-16 18:00

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapimodel',
            name='id',
            field=models.IntegerField(help_text='id', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='testapimodel',
            name='time',
            field=models.FloatField(default=time.time, help_text='时间戳', verbose_name='时间戳'),
        ),
    ]
