# Generated by Django 2.0.7 on 2018-07-16 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0003_auto_20180716_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapimodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='时间', verbose_name='时间'),
        ),
    ]
